### ISSUE TITLE
PPD-EVAC-U-8 Service Airlock - Not Docking

### ISSUE THREAD

**Issue by quade-ksp** [ChrisAdderley/StationPartsExpansionRedux#149]
I've never tried to dock using this port before and I don't know if this is a known issue or not, but I've tried several times and I can't get this docking port to work.

https://youtu.be/-Q-zeSzJics

Currently using
STATION PARTS EXPANSION REDUX v1.0.5

**Comment by ChrisAdderley** [comment]
I have kinda reproduced this, I think there is something wrong with the collider for the tube behind the docking point so it's not capping it off right. You can make it work by disabling SAS/RCS and allowing it to oscillate to the actual stop point via the port's natural attraction. 

I will ship a more comprehensive fix next version.

**Comment by Wyzard256** [comment]
I posted this in the forum already, but just to have it documented here as well, here's an image that shows the missing collider on the docking tube:

![collider](https://user-images.githubusercontent.com/23350503/45656689-d67a0280-bab4-11e8-9772-fe5c0076dbf1.jpg)

(The vessel at the top oscillated for awhile like in the video, but did eventually dock.  I had turned SAS off so that may have helped it align properly.)

**Comment by ChrisAdderley** [comment]
Fixed in 1.0.6

**Comment by quade-ksp** [comment]
Woot!

**Comment by jessicest** [comment]
Is this still fixed? I've been trying to dock for half an hour but it's not working like a normal docking port.

![screenshot441](https://user-images.githubusercontent.com/4454658/141969322-d64634d7-8f44-4ec7-9aaa-a31db38cc92d.png)

**Comment by quade-ksp** [comment]
Received a question via email as to whether or not this is still working.  Just cheated a test article into orbit, undocked and redocked.  Works for me.
![Screen Shot 2021-11-16 at 9 52 07 AM](https://user-images.githubusercontent.com/35043614/142042566-c17811c9-33f4-4a27-a0f7-8b660e2211f9.jpg)
